version: "3.8"

services:

  pocketbase:
    container_name: pocketbase
    build:
      context: .
      dockerfile: docker/pocketbase.Dockerfile
    volumes:
      - pocketbase-data:/pb/pb_data
      - ./migrations:/pb/pb_migrations
    ports:
      - "8080:8080"

  redis:
    container_name: redis
    image: redis:7.2.3-alpine
    restart: always
    env_file:
      - .env
    volumes:
      - redis_data:/var/lib/redis/data/
      - ./config/redis.conf:/usr/local/etc/redis/redis.conf
    command: >
      /usr/local/etc/redis/redis.conf
      --requirepass ${REDIS_PASSWORD}
    ports:
      - 6379:6379

volumes:
  pocketbase-data:
  redis_data: