version: "3.8"

services:
  kong:
    image: kong:3.5.0
    profiles:
      - api
    container_name: kong
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /etc/kong/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: "0.0.0.0:8001"
      KONG_ADMIN_GUI_LISTEN: "0.0.0.0:8002"
    volumes:
      - ./gateway/kong.yml:/etc/kong/kong.yml
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"
    depends_on:
      - api

  pocketbase:
    profiles:
      - db
    container_name: pocketbase
    build:
      context: .
      dockerfile: docker/pocketbase.Dockerfile
    env_file:
      - .env
    volumes:
      - pocketbase-data:/pb/pb_data
      - ./migrations:/pb/pb_migrations
    ports:
      - "8080:8080"

  redis:
    profiles:
      - db
    container_name: redis
    image: redis:7.2.3-alpine
    restart: always
    volumes:
      - redis_data:/var/lib/redis/data/
      - ./config/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"

  qdrant:
    profiles:
      - db
    container_name: qdrant
    image: qdrant/qdrant:v1.7.3
    restart: always
    volumes:
      - qdrant_data:/qdrant/storage
    ports:
      - "6333:6333"

  api:
    profiles:
      - api
    container_name: api
    build:
      context: .
      dockerfile: docker/python.Dockerfile
      target: api
    ports:
      - "8000"
    depends_on:
      - pocketbase
      - qdrant

volumes:
  pocketbase-data:
  redis_data:
  qdrant_data:
  pgdata:
