version: "3.8"

services:
  pocketbase:
    container_name: pocketbase
    build:
      context: .
      dockerfile: docker/pocketbase.Dockerfile
    volumes:
      - pocketbase-data:/pb/pb_data
      - ./migrations:/pb/pb_migrations
    ports:
      - "8080:8080"

  redis:
    container_name: redis
    image: redis:7.2.3-alpine
    restart: always
    env_file:
      - .env.prod
    volumes:
      - redis_data:/var/lib/redis/data/
      - ./config/redis.conf:/usr/local/etc/redis/redis.conf
    command: >
      /usr/local/etc/redis/redis.conf
      --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"

  qdrant:
    container_name: qdrant
    image: qdrant/qdrant:v1.7.3
    restart: always
    env_file:
      - .env.prod
    volumes:
      - qdrant_data:/qdrant/storage:z
    ports:
      - "6333:6333"

  api:
    container_name: api
    build:
      context: .
      dockerfile: docker/api.Dockerfile
    env_file:
      - .env.prod
    ports:
      - "8000:80"
    depends_on:
      - pocketbase
      - qdrant

  worker:
    container_name: worker
    build:
      context: .
      dockerfile: docker/api.Dockerfile
    command: celery -A workers.app worker -l debug
    env_file:
      - .env.prod
    depends_on:
      - pocketbase
      - qdrant
      - redis

volumes:
  pocketbase-data:
  redis_data:
  qdrant_data:
