version: "3.8"

services:

  pocketbase:
    container_name: pocketbase
    build:
      context: .
      dockerfile: docker/pocketbase.Dockerfile
    volumes:
      - pocketbase-data:/pb/pb_data
      - ./migrations:/pb/pb_migrations
    ports:
      - "8080:8080"

  redis:
    container_name: redis
    image: redis:7.2.3-alpine
    restart: always
    env_file:
      - .env
    volumes:
      - redis_data:/var/lib/redis/data/
      - ./config/redis.conf:/usr/local/etc/redis/redis.conf
    command: >
      /usr/local/etc/redis/redis.conf
      --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"

  qdrant:
    container_name: qdrant
    image: qdrant/qdrant:v1.7.3
    restart: always
    env_file:
      - .env
    volumes:
      - qdrant_data:/qdrant/storage:z
    ports:
      - "6333:6333"

  ollama:
    container_name: ollama
    image: ollama/ollama:0.1.17
    restart: always
    volumes:
      - ollama_data:/root/.ollama
    entrypoint: docker/ollama.entrypoint.sh
    ports:
      - "11434:11434"

volumes:
  pocketbase-data:
  redis_data:
  qdrant_data:
  ollama_data: