version: "3.8"

services:
  pocketbase:
    profiles:
      - db
    container_name: pocketbase
    build:
      context: .
      dockerfile: docker/pocketbase.Dockerfile
    volumes:
      - pocketbase-data:/pb/pb_data
      - ./migrations:/pb/pb_migrations
    ports:
      - "8080:8080"

  redis:
    profiles:
      - db
    container_name: redis
    image: redis:7.2.3-alpine
    restart: always
    env_file:
      - .env
    volumes:
      - redis_data:/var/lib/redis/data/
      - ./config/redis.conf:/usr/local/etc/redis/redis.conf
    command: >
      /usr/local/etc/redis/redis.conf
      --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"

  qdrant:
    profiles:
      - db
    container_name: qdrant
    image: qdrant/qdrant:v1.7.3
    restart: always
    volumes:
      - qdrant_data:/qdrant/storage
    ports:
      - "6333:6333"

  api:
    profiles:
      - api
    container_name: api
    build:
      context: .
      dockerfile: docker/api.Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - pocketbase
      - qdrant

  worker:
    profiles:
      - worker
    container_name: worker
    build:
      context: .
      dockerfile: docker/api.Dockerfile
    command: celery -A workers.app worker -l info
    depends_on:
      - pocketbase
      - qdrant
      - redis

  flower:
    profiles:
      - worker
    container_name: flower
    build:
      context: .
      dockerfile: docker/api.Dockerfile
    command: celery -A workers.app flower -l info
    ports:
      - "5555:5555"
    depends_on:
      - worker
      - redis

  embedding-service:
    profiles:
      - ai
    container_name: embedding-service
    build:
      context: .
      dockerfile: docker/ai.Dockerfile
      target: ai
      args:
        - APP_NAME=embedding
    ports:
      - "9000:80"

  qa-service:
    profiles:
      - ai
    container_name: qa-service
    build:
      context: .
      dockerfile: docker/ai.Dockerfile
      target: ai
      args:
        - APP_NAME=question_answering
    ports:
      - "9001:80"

  ollama:
    profiles:
      - ollama
    container_name: ollama
    image: ollama/ollama:0.1.17
    restart: always
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"

  summarizer-service:
    profiles:
      - ai
    container_name: summarizer-service
    build:
      context: .
      dockerfile: docker/ai.Dockerfile
      target: ai
      args:
        - APP_NAME=summarizer
    ports:
      - "9002:80"

volumes:
  pocketbase-data:
  redis_data:
  qdrant_data:
  ollama_data: