redis:
  host: localhost
  port: 6379
  db: 0
  password: Xz2nIEktE4

qdrant:
  url: http://localhost:6333/

pocketbase:
  url: http://localhost:8080/


celery:
  broker_url: redis://:Xz2nIEktE4@localhost:6379/1
  result_backend: redis://:Xz2nIEktE4@localhost:6379/2


api:
  url: http://localhost:8000/

summarizer:
  type: base
  model: Falconsai/text_summarization
  url: http://localhost:9000/summarize/

embedding:
  type: base
  model: all-MiniLM-L6-v2
  url: http://localhost:9001/embedding/

qa:
  type: base
  model: google/flan-t5-base
  url: http://localhost:9002/answer/

openai:
  key: sk-2x2x2x2x2x